default: &default
  adapter: postgresql
  host: <%= ENV['DATABASE_URL'] || 'localhost' %>
  encoding: unicode
  username: <%= ENV['DATABASE_USERNAME'] || nil %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: meetings_development

test:
  <<: *default
  database: meetings_test
  port: 5432

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
